### PR TITLE
Colemickens test prep

### PR DESCRIPTION
**Pull request by colemickens**

### CODE REVIEW

**Comment by colemickens** [comment]
@acs-bot unit test this

**Comment by colemickens** [comment]
@acs-bot validate k8s

**Comment by dummyaccountant** [comment]
acs-engine unit tests [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-unit-tests/4/) for commit a258bb383f98f712a2407a6020badfb204f99e6c. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot unit test this`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/42/) for commit a258bb383f98f712a2407a6020badfb204f99e6c. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine unit tests [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-unit-tests/5/) for commit a258bb383f98f712a2407a6020badfb204f99e6c. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot unit test this`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/43/) for commit a258bb383f98f712a2407a6020badfb204f99e6c. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/44/) for commit a258bb383f98f712a2407a6020badfb204f99e6c. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/45/) for commit a258bb383f98f712a2407a6020badfb204f99e6c. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/46/) for commit a258bb383f98f712a2407a6020badfb204f99e6c. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s cm [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s-cm/18/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s cm`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/49/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s cm [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s-cm/19/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s cm`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s cm [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s-cm/20/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s cm`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/51/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s cm [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s-cm/21/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s cm`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/53/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s cm [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s-cm/22/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s cm`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/56/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s cm [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s-cm/23/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s cm`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s cm [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s-cm/24/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s cm`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/58/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s cm [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s-cm/25/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s cm`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/60/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s cm [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s-cm/26/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s cm`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Comment by dummyaccountant** [comment]
acs-engine validate k8s [**failed**](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/colemickens_acs-engine/12/pr-acs-engine-validate-k8s/62/) for commit 831df6957b9e25af22636dc4f68a6dfbf3c8ac59. [Full PR test history](http://pr-test.k8s.io/colemickens_acs-engine/12). 

cc @colemickens, [your PR dashboard](https://k8s-gubernator.appspot.com/pr/colemickens)

The magic incantation to run this job again is `@acs-bot validate k8s`. Please help us cut down flakes by linking to an [open flake issue](https://github.com/colemickens/acs-engine/issues?q=is:issue+label:kind/flake+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

**Pull request closed without merging**
